// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alatMedis.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	alatMedis.proto

It has these top-level messages:
	AddAlatMedisReq
	ReadAlatMedisByKodeReq
	ReadAlatMedisByKodeResp
	ReadAlatMedisByStatusReq
	ReadAlatMedisByStatusResp
	ReadAlatMedisResp
	UpdateAlatMedisReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddAlatMedisReq struct {
	KodeAlatMedis string `protobuf:"bytes,1,opt,name=kodeAlatMedis" json:"kodeAlatMedis,omitempty"`
	NamaAlatMedis string `protobuf:"bytes,2,opt,name=namaAlatMedis" json:"namaAlatMedis,omitempty"`
	Biaya         int64  `protobuf:"varint,3,opt,name=biaya" json:"biaya,omitempty"`
	Deskripsi     string `protobuf:"bytes,4,opt,name=deskripsi" json:"deskripsi,omitempty"`
	CreatedBy     string `protobuf:"bytes,5,opt,name=createdBy" json:"createdBy,omitempty"`
	CreatedOn     string `protobuf:"bytes,6,opt,name=createdOn" json:"createdOn,omitempty"`
	Status        string `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
}

func (m *AddAlatMedisReq) Reset()                    { *m = AddAlatMedisReq{} }
func (m *AddAlatMedisReq) String() string            { return proto.CompactTextString(m) }
func (*AddAlatMedisReq) ProtoMessage()               {}
func (*AddAlatMedisReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddAlatMedisReq) GetKodeAlatMedis() string {
	if m != nil {
		return m.KodeAlatMedis
	}
	return ""
}

func (m *AddAlatMedisReq) GetNamaAlatMedis() string {
	if m != nil {
		return m.NamaAlatMedis
	}
	return ""
}

func (m *AddAlatMedisReq) GetBiaya() int64 {
	if m != nil {
		return m.Biaya
	}
	return 0
}

func (m *AddAlatMedisReq) GetDeskripsi() string {
	if m != nil {
		return m.Deskripsi
	}
	return ""
}

func (m *AddAlatMedisReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *AddAlatMedisReq) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *AddAlatMedisReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// request adalah yang datang lalu ditampung
type ReadAlatMedisByKodeReq struct {
	Kode string `protobuf:"bytes,1,opt,name=kode" json:"kode,omitempty"`
}

func (m *ReadAlatMedisByKodeReq) Reset()                    { *m = ReadAlatMedisByKodeReq{} }
func (m *ReadAlatMedisByKodeReq) String() string            { return proto.CompactTextString(m) }
func (*ReadAlatMedisByKodeReq) ProtoMessage()               {}
func (*ReadAlatMedisByKodeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadAlatMedisByKodeReq) GetKode() string {
	if m != nil {
		return m.Kode
	}
	return ""
}

// request adalah sesuatu yang return yang akan dikembalikan biasanya ada request dan respon
type ReadAlatMedisByKodeResp struct {
	KodeAlatMedis string `protobuf:"bytes,1,opt,name=kodeAlatMedis" json:"kodeAlatMedis,omitempty"`
	NamaAlatMedis string `protobuf:"bytes,2,opt,name=namaAlatMedis" json:"namaAlatMedis,omitempty"`
	Biaya         int64  `protobuf:"varint,3,opt,name=biaya" json:"biaya,omitempty"`
	Deskripsi     string `protobuf:"bytes,4,opt,name=deskripsi" json:"deskripsi,omitempty"`
	CreatedBy     string `protobuf:"bytes,5,opt,name=createdBy" json:"createdBy,omitempty"`
	CreatedOn     string `protobuf:"bytes,6,opt,name=createdOn" json:"createdOn,omitempty"`
	UpdateBy      string `protobuf:"bytes,7,opt,name=updateBy" json:"updateBy,omitempty"`
	UpdateOn      string `protobuf:"bytes,8,opt,name=updateOn" json:"updateOn,omitempty"`
	Status        string `protobuf:"bytes,9,opt,name=status" json:"status,omitempty"`
}

func (m *ReadAlatMedisByKodeResp) Reset()                    { *m = ReadAlatMedisByKodeResp{} }
func (m *ReadAlatMedisByKodeResp) String() string            { return proto.CompactTextString(m) }
func (*ReadAlatMedisByKodeResp) ProtoMessage()               {}
func (*ReadAlatMedisByKodeResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadAlatMedisByKodeResp) GetKodeAlatMedis() string {
	if m != nil {
		return m.KodeAlatMedis
	}
	return ""
}

func (m *ReadAlatMedisByKodeResp) GetNamaAlatMedis() string {
	if m != nil {
		return m.NamaAlatMedis
	}
	return ""
}

func (m *ReadAlatMedisByKodeResp) GetBiaya() int64 {
	if m != nil {
		return m.Biaya
	}
	return 0
}

func (m *ReadAlatMedisByKodeResp) GetDeskripsi() string {
	if m != nil {
		return m.Deskripsi
	}
	return ""
}

func (m *ReadAlatMedisByKodeResp) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *ReadAlatMedisByKodeResp) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *ReadAlatMedisByKodeResp) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *ReadAlatMedisByKodeResp) GetUpdateOn() string {
	if m != nil {
		return m.UpdateOn
	}
	return ""
}

func (m *ReadAlatMedisByKodeResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// request adalah yang datang lalu ditampung
type ReadAlatMedisByStatusReq struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *ReadAlatMedisByStatusReq) Reset()                    { *m = ReadAlatMedisByStatusReq{} }
func (m *ReadAlatMedisByStatusReq) String() string            { return proto.CompactTextString(m) }
func (*ReadAlatMedisByStatusReq) ProtoMessage()               {}
func (*ReadAlatMedisByStatusReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadAlatMedisByStatusReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// request adalah sesuatu yang return yang akan dikembalikan biasanya ada request dan respon
type ReadAlatMedisByStatusResp struct {
	KodeAlatMedis string `protobuf:"bytes,1,opt,name=kodeAlatMedis" json:"kodeAlatMedis,omitempty"`
	NamaAlatMedis string `protobuf:"bytes,2,opt,name=namaAlatMedis" json:"namaAlatMedis,omitempty"`
	Biaya         int64  `protobuf:"varint,3,opt,name=biaya" json:"biaya,omitempty"`
	Deskripsi     string `protobuf:"bytes,4,opt,name=deskripsi" json:"deskripsi,omitempty"`
	CreatedBy     string `protobuf:"bytes,5,opt,name=createdBy" json:"createdBy,omitempty"`
	CreatedOn     string `protobuf:"bytes,6,opt,name=createdOn" json:"createdOn,omitempty"`
	UpdateBy      string `protobuf:"bytes,7,opt,name=updateBy" json:"updateBy,omitempty"`
	UpdateOn      string `protobuf:"bytes,8,opt,name=updateOn" json:"updateOn,omitempty"`
	Status        string `protobuf:"bytes,9,opt,name=status" json:"status,omitempty"`
}

func (m *ReadAlatMedisByStatusResp) Reset()                    { *m = ReadAlatMedisByStatusResp{} }
func (m *ReadAlatMedisByStatusResp) String() string            { return proto.CompactTextString(m) }
func (*ReadAlatMedisByStatusResp) ProtoMessage()               {}
func (*ReadAlatMedisByStatusResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadAlatMedisByStatusResp) GetKodeAlatMedis() string {
	if m != nil {
		return m.KodeAlatMedis
	}
	return ""
}

func (m *ReadAlatMedisByStatusResp) GetNamaAlatMedis() string {
	if m != nil {
		return m.NamaAlatMedis
	}
	return ""
}

func (m *ReadAlatMedisByStatusResp) GetBiaya() int64 {
	if m != nil {
		return m.Biaya
	}
	return 0
}

func (m *ReadAlatMedisByStatusResp) GetDeskripsi() string {
	if m != nil {
		return m.Deskripsi
	}
	return ""
}

func (m *ReadAlatMedisByStatusResp) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *ReadAlatMedisByStatusResp) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *ReadAlatMedisByStatusResp) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *ReadAlatMedisByStatusResp) GetUpdateOn() string {
	if m != nil {
		return m.UpdateOn
	}
	return ""
}

func (m *ReadAlatMedisByStatusResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReadAlatMedisResp struct {
	// repeated itu sama kayak menulis ulang
	Allkode []*ReadAlatMedisByKodeResp `protobuf:"bytes,1,rep,name=allkode" json:"allkode,omitempty"`
}

func (m *ReadAlatMedisResp) Reset()                    { *m = ReadAlatMedisResp{} }
func (m *ReadAlatMedisResp) String() string            { return proto.CompactTextString(m) }
func (*ReadAlatMedisResp) ProtoMessage()               {}
func (*ReadAlatMedisResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadAlatMedisResp) GetAllkode() []*ReadAlatMedisByKodeResp {
	if m != nil {
		return m.Allkode
	}
	return nil
}

type UpdateAlatMedisReq struct {
	KodeAlatMedis string `protobuf:"bytes,1,opt,name=kodeAlatMedis" json:"kodeAlatMedis,omitempty"`
	NamaAlatMedis string `protobuf:"bytes,2,opt,name=namaAlatMedis" json:"namaAlatMedis,omitempty"`
	Biaya         int64  `protobuf:"varint,3,opt,name=biaya" json:"biaya,omitempty"`
	Deskripsi     string `protobuf:"bytes,4,opt,name=deskripsi" json:"deskripsi,omitempty"`
	UpdateBy      string `protobuf:"bytes,5,opt,name=updateBy" json:"updateBy,omitempty"`
	UpdateOn      string `protobuf:"bytes,6,opt,name=updateOn" json:"updateOn,omitempty"`
	Status        string `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
}

func (m *UpdateAlatMedisReq) Reset()                    { *m = UpdateAlatMedisReq{} }
func (m *UpdateAlatMedisReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateAlatMedisReq) ProtoMessage()               {}
func (*UpdateAlatMedisReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateAlatMedisReq) GetKodeAlatMedis() string {
	if m != nil {
		return m.KodeAlatMedis
	}
	return ""
}

func (m *UpdateAlatMedisReq) GetNamaAlatMedis() string {
	if m != nil {
		return m.NamaAlatMedis
	}
	return ""
}

func (m *UpdateAlatMedisReq) GetBiaya() int64 {
	if m != nil {
		return m.Biaya
	}
	return 0
}

func (m *UpdateAlatMedisReq) GetDeskripsi() string {
	if m != nil {
		return m.Deskripsi
	}
	return ""
}

func (m *UpdateAlatMedisReq) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *UpdateAlatMedisReq) GetUpdateOn() string {
	if m != nil {
		return m.UpdateOn
	}
	return ""
}

func (m *UpdateAlatMedisReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*AddAlatMedisReq)(nil), "grpc.AddAlatMedisReq")
	proto.RegisterType((*ReadAlatMedisByKodeReq)(nil), "grpc.ReadAlatMedisByKodeReq")
	proto.RegisterType((*ReadAlatMedisByKodeResp)(nil), "grpc.ReadAlatMedisByKodeResp")
	proto.RegisterType((*ReadAlatMedisByStatusReq)(nil), "grpc.ReadAlatMedisByStatusReq")
	proto.RegisterType((*ReadAlatMedisByStatusResp)(nil), "grpc.ReadAlatMedisByStatusResp")
	proto.RegisterType((*ReadAlatMedisResp)(nil), "grpc.ReadAlatMedisResp")
	proto.RegisterType((*UpdateAlatMedisReq)(nil), "grpc.UpdateAlatMedisReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for AlatMedisService service

type AlatMedisServiceClient interface {
	AddAlatMedis(ctx context.Context, in *AddAlatMedisReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadAlatMedisByKode(ctx context.Context, in *ReadAlatMedisByKodeReq, opts ...grpc1.CallOption) (*ReadAlatMedisByKodeResp, error)
	ReadAlatMedisByStatus(ctx context.Context, in *ReadAlatMedisByStatusReq, opts ...grpc1.CallOption) (*ReadAlatMedisByStatusResp, error)
	ReadAlatMedis(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadAlatMedisResp, error)
	UpdateAlatMedis(ctx context.Context, in *UpdateAlatMedisReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
}

type alatMedisServiceClient struct {
	cc *grpc1.ClientConn
}

func NewAlatMedisServiceClient(cc *grpc1.ClientConn) AlatMedisServiceClient {
	return &alatMedisServiceClient{cc}
}

func (c *alatMedisServiceClient) AddAlatMedis(ctx context.Context, in *AddAlatMedisReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AlatMedisService/AddAlatMedis", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alatMedisServiceClient) ReadAlatMedisByKode(ctx context.Context, in *ReadAlatMedisByKodeReq, opts ...grpc1.CallOption) (*ReadAlatMedisByKodeResp, error) {
	out := new(ReadAlatMedisByKodeResp)
	err := grpc1.Invoke(ctx, "/grpc.AlatMedisService/ReadAlatMedisByKode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alatMedisServiceClient) ReadAlatMedisByStatus(ctx context.Context, in *ReadAlatMedisByStatusReq, opts ...grpc1.CallOption) (*ReadAlatMedisByStatusResp, error) {
	out := new(ReadAlatMedisByStatusResp)
	err := grpc1.Invoke(ctx, "/grpc.AlatMedisService/ReadAlatMedisByStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alatMedisServiceClient) ReadAlatMedis(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadAlatMedisResp, error) {
	out := new(ReadAlatMedisResp)
	err := grpc1.Invoke(ctx, "/grpc.AlatMedisService/ReadAlatMedis", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alatMedisServiceClient) UpdateAlatMedis(ctx context.Context, in *UpdateAlatMedisReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AlatMedisService/UpdateAlatMedis", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AlatMedisService service

type AlatMedisServiceServer interface {
	AddAlatMedis(context.Context, *AddAlatMedisReq) (*google_protobuf.Empty, error)
	ReadAlatMedisByKode(context.Context, *ReadAlatMedisByKodeReq) (*ReadAlatMedisByKodeResp, error)
	ReadAlatMedisByStatus(context.Context, *ReadAlatMedisByStatusReq) (*ReadAlatMedisByStatusResp, error)
	ReadAlatMedis(context.Context, *google_protobuf.Empty) (*ReadAlatMedisResp, error)
	UpdateAlatMedis(context.Context, *UpdateAlatMedisReq) (*google_protobuf.Empty, error)
}

func RegisterAlatMedisServiceServer(s *grpc1.Server, srv AlatMedisServiceServer) {
	s.RegisterService(&_AlatMedisService_serviceDesc, srv)
}

func _AlatMedisService_AddAlatMedis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAlatMedisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlatMedisServiceServer).AddAlatMedis(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AlatMedisService/AddAlatMedis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlatMedisServiceServer).AddAlatMedis(ctx, req.(*AddAlatMedisReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlatMedisService_ReadAlatMedisByKode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAlatMedisByKodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlatMedisServiceServer).ReadAlatMedisByKode(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AlatMedisService/ReadAlatMedisByKode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlatMedisServiceServer).ReadAlatMedisByKode(ctx, req.(*ReadAlatMedisByKodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlatMedisService_ReadAlatMedisByStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAlatMedisByStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlatMedisServiceServer).ReadAlatMedisByStatus(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AlatMedisService/ReadAlatMedisByStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlatMedisServiceServer).ReadAlatMedisByStatus(ctx, req.(*ReadAlatMedisByStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlatMedisService_ReadAlatMedis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlatMedisServiceServer).ReadAlatMedis(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AlatMedisService/ReadAlatMedis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlatMedisServiceServer).ReadAlatMedis(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlatMedisService_UpdateAlatMedis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlatMedisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlatMedisServiceServer).UpdateAlatMedis(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AlatMedisService/UpdateAlatMedis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlatMedisServiceServer).UpdateAlatMedis(ctx, req.(*UpdateAlatMedisReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlatMedisService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.AlatMedisService",
	HandlerType: (*AlatMedisServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddAlatMedis",
			Handler:    _AlatMedisService_AddAlatMedis_Handler,
		},
		{
			MethodName: "ReadAlatMedisByKode",
			Handler:    _AlatMedisService_ReadAlatMedisByKode_Handler,
		},
		{
			MethodName: "ReadAlatMedisByStatus",
			Handler:    _AlatMedisService_ReadAlatMedisByStatus_Handler,
		},
		{
			MethodName: "ReadAlatMedis",
			Handler:    _AlatMedisService_ReadAlatMedis_Handler,
		},
		{
			MethodName: "UpdateAlatMedis",
			Handler:    _AlatMedisService_UpdateAlatMedis_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "alatMedis.proto",
}

func init() { proto.RegisterFile("alatMedis.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x94, 0x41, 0xaf, 0x9a, 0x40,
	0x10, 0xc7, 0x45, 0x14, 0x75, 0x5a, 0x63, 0xbb, 0xad, 0xba, 0xa5, 0xb6, 0x35, 0xa4, 0x07, 0x0f,
	0x0d, 0x26, 0xf6, 0xd0, 0x63, 0x23, 0x89, 0xa7, 0xb6, 0x31, 0xc1, 0xf6, 0xd2, 0xdb, 0xea, 0x6e,
	0x0d, 0x11, 0x01, 0x01, 0x9b, 0xf0, 0x2d, 0xfa, 0x25, 0x9a, 0x7e, 0xb1, 0xbe, 0xef, 0xf1, 0xc2,
	0x82, 0xc0, 0xfa, 0x80, 0xf3, 0x7b, 0xc9, 0xbb, 0xb1, 0xf3, 0xff, 0xcf, 0xc2, 0xfc, 0x98, 0x19,
	0x18, 0x10, 0x9b, 0x84, 0xdf, 0x18, 0xb5, 0x02, 0xdd, 0xf3, 0xdd, 0xd0, 0x45, 0xad, 0xbd, 0xef,
	0xed, 0xd4, 0xd7, 0x7b, 0xd7, 0xdd, 0xdb, 0x6c, 0xce, 0x63, 0xdb, 0xf3, 0xaf, 0x39, 0x3b, 0x7a,
	0x61, 0x94, 0x58, 0xb4, 0x1b, 0x09, 0x06, 0x4b, 0x4a, 0x97, 0x97, 0x4c, 0x93, 0x9d, 0xd0, 0x7b,
	0xe8, 0x1f, 0x5c, 0xca, 0xb2, 0x18, 0x96, 0xa6, 0xd2, 0xac, 0x67, 0x8a, 0xc1, 0xd8, 0xe5, 0x90,
	0x23, 0xc9, 0x5d, 0xcd, 0xc4, 0x25, 0x04, 0xd1, 0x4b, 0x68, 0x6f, 0x2d, 0x12, 0x11, 0x2c, 0x4f,
	0xa5, 0x99, 0x6c, 0x26, 0x07, 0x34, 0x81, 0x1e, 0x65, 0xc1, 0xc1, 0xb7, 0xbc, 0xc0, 0xc2, 0x2d,
	0x9e, 0x97, 0x07, 0x62, 0x75, 0xe7, 0x33, 0x12, 0x32, 0x6a, 0x44, 0xb8, 0x9d, 0xa8, 0x59, 0xa0,
	0xa0, 0xae, 0x1d, 0xac, 0x08, 0xea, 0xda, 0x41, 0x23, 0x50, 0x82, 0x90, 0x84, 0xe7, 0x00, 0x77,
	0xb8, 0x94, 0x9e, 0xb4, 0x0f, 0x30, 0x32, 0x19, 0xc9, 0xeb, 0x34, 0xa2, 0x2f, 0x2e, 0x65, 0x71,
	0xb5, 0x08, 0x5a, 0x71, 0x61, 0x69, 0x91, 0xfc, 0x59, 0xfb, 0xdb, 0x84, 0x71, 0xa9, 0x3d, 0xf0,
	0x1e, 0x34, 0x1d, 0x15, 0xba, 0x67, 0x8f, 0x92, 0x90, 0x19, 0x51, 0xca, 0x27, 0x3b, 0xe7, 0xda,
	0xda, 0xc1, 0xdd, 0xa2, 0x26, 0x50, 0xed, 0x09, 0x54, 0x17, 0x80, 0xaf, 0x30, 0x6d, 0xb8, 0x10,
	0x73, 0xcd, 0x73, 0x24, 0x21, 0xe7, 0x5f, 0x13, 0x5e, 0x55, 0x24, 0x3d, 0xd2, 0x15, 0x48, 0x7d,
	0x85, 0xe7, 0x02, 0x28, 0x0e, 0xe8, 0x13, 0x74, 0x88, 0x6d, 0xa7, 0x1d, 0x2b, 0xcf, 0x9e, 0x2c,
	0xde, 0xe8, 0xf1, 0x94, 0xeb, 0x15, 0xed, 0x6a, 0x5e, 0xdc, 0xda, 0x7f, 0x09, 0xd0, 0x0f, 0xfe,
	0xca, 0x7b, 0x35, 0xec, 0x45, 0x68, 0xed, 0x1a, 0x68, 0x4a, 0x25, 0x34, 0x61, 0xd0, 0x17, 0x7f,
	0x64, 0x78, 0x96, 0x7d, 0xd1, 0x86, 0xf9, 0xbf, 0xad, 0x1d, 0x43, 0x9f, 0xe1, 0x69, 0x71, 0xc9,
	0xa1, 0x61, 0xc2, 0xec, 0x6a, 0xf1, 0xa9, 0x23, 0x3d, 0x59, 0x95, 0xfa, 0x65, 0x55, 0xea, 0xab,
	0x78, 0x55, 0x6a, 0x0d, 0xf4, 0x1d, 0x5e, 0x94, 0x00, 0x46, 0x93, 0x1a, 0xf6, 0x27, 0xb5, 0xfe,
	0xcf, 0x68, 0x0d, 0xf4, 0x13, 0x86, 0xa5, 0x93, 0x80, 0xde, 0x96, 0x66, 0x66, 0xb3, 0xa5, 0xbe,
	0xab, 0xd5, 0xf9, 0xdd, 0x06, 0xf4, 0x05, 0x19, 0x55, 0x14, 0xa7, 0x8e, 0x4b, 0xee, 0x4a, 0xef,
	0x58, 0xc1, 0xe0, 0xaa, 0x63, 0x10, 0x4e, 0xdc, 0x77, 0x1b, 0xa9, 0x1a, 0xde, 0x56, 0xe1, 0x91,
	0x8f, 0xb7, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x25, 0xb8, 0xc1, 0xa0, 0x06, 0x00, 0x00,
}
